id: rel01.0-uc002-generation-lifecycle
title: Generation Lifecycle from Start to Stop

summary: |
  A developer starts a new generation, runs measure+stitch cycles to
  build code on the generation branch, and stops the generation to
  merge the result into main. The entire lifecycle is managed through
  Mage targets without manual git operations.

actor: Developer running Mage targets for code generation

trigger: Running mage generator:start to begin a new generation

flow:
  - F1: "Start generation: call GeneratorStart() which tags main, creates a generation branch, resets Go sources, and commits clean state"
  - F2: "Run cycles: call GeneratorRun() to execute Config.Cycles measure+stitch cycles on the generation branch"
  - F3: "Monitor progress: call GeneratorList() to see active generations and their lifecycle tags"
  - F4: "Stop generation: call GeneratorStop() which tags the generation, switches to main, merges, restores code from earlier generations, tags the result, and deletes the branch"
  - F5: "Verify: confirm main has the generated code and the generation branch is deleted"

touchpoints:
  - T1: "GeneratorStart: prd002-generation-lifecycle R2"
  - T2: "GeneratorRun/RunCycles: prd002-generation-lifecycle R3"
  - T3: "GeneratorStop: prd002-generation-lifecycle R5"
  - T4: "GeneratorList: prd002-generation-lifecycle R7"
  - T5: "Git operations: tags, branches, merges via pkg/orchestrator/commands.go"

success_criteria:
  - S1: GeneratorStart creates a generation branch with clean state and start tag
  - S2: GeneratorRun executes the specified number of cycles
  - S3: GeneratorStop merges to main with finished and merged tags
  - S4: The generation branch is deleted after successful stop
  - S5: Main contains the generated code and code from earlier generations

out_of_scope:
  - Content of measure and stitch workflows (see rel01.0-uc003, rel01.0-uc004)
  - Recovery from interrupted runs (see rel01.0-uc005)

